# Variabler
CXX = g++
CXXFLAGS = -O2 -Wall

# Namnet på din körbara fil
TARGET = problemA

all: $(TARGET)

$(TARGET): problemA.cpp
	$(CXX) $(CXXFLAGS) problemA.cpp -o $(TARGET)

clean:
	rm -f $(TARGET)